// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh2LxdLkTXpn_T_s-HVxUoUzFFEQdhOGE',
    appId: '1:273298947500:web:14525609b80d72985f4e09',
    messagingSenderId: '273298947500',
    projectId: 'hw22-20715',
    authDomain: 'hw22-20715.firebaseapp.com',
    storageBucket: 'hw22-20715.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhdtxhzlkaG2BmaO90BsUpH6RZMuNxow',
    appId: '1:273298947500:android:97e6abb465eb93515f4e09',
    messagingSenderId: '273298947500',
    projectId: 'hw22-20715',
    storageBucket: 'hw22-20715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-GlFBcMy6JPvmMx1XkFgKZUbe89AOWk',
    appId: '1:273298947500:ios:6ca67b60eee510225f4e09',
    messagingSenderId: '273298947500',
    projectId: 'hw22-20715',
    storageBucket: 'hw22-20715.firebasestorage.app',
    iosBundleId: 'com.example.messageboardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK-GlFBcMy6JPvmMx1XkFgKZUbe89AOWk',
    appId: '1:273298947500:ios:6ca67b60eee510225f4e09',
    messagingSenderId: '273298947500',
    projectId: 'hw22-20715',
    storageBucket: 'hw22-20715.firebasestorage.app',
    iosBundleId: 'com.example.messageboardapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh2LxdLkTXpn_T_s-HVxUoUzFFEQdhOGE',
    appId: '1:273298947500:web:cef44f219497150b5f4e09',
    messagingSenderId: '273298947500',
    projectId: 'hw22-20715',
    authDomain: 'hw22-20715.firebaseapp.com',
    storageBucket: 'hw22-20715.firebasestorage.app',
  );

}